export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';
export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';

export const LOGIN_USER = 'LOGIN_USER';
export const ATTEMPTING_LOGIN = 'ATTEMPTING_LOGIN';
export const LOGOUT = 'LOGOUT';
export const ANONYMOUS = 'ANONYMOUS';
export const AWAITING_AUTH_RESPONSE = 'AWAITING_AUTH_RESPONSE';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';